### ISSUE TITLE
Commit Group milestone 2

### ISSUE THREAD

**Issue by leo-le-07** [middle-guys/iflight#22]
Dear @coderschoolreview,

Our team attach the submission for this milestone. We also attach some workflows in the comments below with description for each workflow. Please help use check them.

Thanks
## Vision Statements
- Finding and booking airline tickets
- Cheap price alert
- Customer service is supported by AI bots
## Done
- [x] Home page with event handler
- [x] Layout Flights result page (not binding data from server)
- [x] User sign up
- [x] User sign in
- [x] User sign in with remember me option
- [x] Crawl ticket price (Vietjet Air, Vietnam Airline, Jetstar) feature
## Remain work
- Booking service
- Notification service
- AI Bots chat service
